### ISSUE TITLE
react-input-placeholder is not compatible with React v.13

### ISSUE THREAD

**Issue by vguzev** [enigma-io/react-input-placeholder#13]
Current version of react-input-placeholder (v.1.0.0 installed via npm) is not working with React v.13.3.
It throws exception:
<code>Uncaught TypeError: this.transferPropsTo is not a function @ react-input-placeholder.js?0ea3:84</code>

transferPropsTo was removed from React in v.13.

**Comment by yaycmyk** [comment]
@vguzev Will investigate, thanks.

**Comment by yaycmyk** [comment]
@vguzev Not sure why you're getting this error - transferPropsTo is only triggered if the version of React being used doesn't have the `createElement` function, which 0.12+ does.
