### ISSUE TITLE
Don't work for ie9

### ISSUE THREAD

**Issue by webelart** [enigma-io/react-input-placeholder#16]
Hi, Evan! First of all, thank you for your library, it's really need. 

I need help. When i installed the plugin, it hadn't worked. In the ie9 for an input placeholder == value, and when i try to change value the input, placeholder doesn't remove and my new chars don't add. I have tried to understand you code and i think that everything is right and i can't catch any errors. May you check your plugin? Is it really work now?

**Comment by quantizor** [comment]
@liveldi90 Could you give a small example of how you are using it? The placeholder works based on the `onChange` event, so if you're changing the value programmatically, you may need to take an additional step to trigger the necessary events.

**Comment by webelart** [comment]
@yaycmyk Example my code:

``` javascript
var Input = require('react-input-placeholder')(React).Input;

var AuthSignIn = React.createClass({
    render: function () {
         <Input id="phone" autoComplete="off" ref="phone" placeholder="Телефон или email" />
    }
});
```

It's a short example. And I haven't any function for `onChange`, only your plugin. But when i try to use `onCnange` in the react class, then all work right:

``` javascript
var AuthSignIn = React.createClass({
    .....
    onCnange: function () {
         this.setState({
              input: e.target.value
         })
    },
    render: function () {
         <Input id="phone" autoComplete="off" ref="phone" placeholder="Телефон или email" value={this.state.input}/>
    }
});
```

But i don't want to add `onChange` function to every component . My program have so many `input` and `textarea`. :(

I think may be `React.createElement` don't allow to change value after creating...

**Comment by quantizor** [comment]
You're not actually using `onChange` in the `<Input />`
