### ISSUE TITLE
"Warning: Input.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead."

### ISSUE THREAD

**Issue by craigdallimore** [enigma-io/react-input-placeholder#17]
It looks like like this polyfill is using a [deprecated](https://github.com/facebook/react/blob/master/CHANGELOG.md#deprecations) method "`.getDOMNode()`" [here](https://github.com/facebook/react/blob/master/CHANGELOG.md#deprecations). This produces a deprecation warning in the console when used with `react@0.14.x`.

<img width="395" alt="screen shot 2015-11-23 at 14 34 32" src="https://cloud.githubusercontent.com/assets/926283/11339161/1775e934-91f0-11e5-9a42-e48258f290cd.png">

Looks like all it needs is the presence of [react-dom](https://www.npmjs.com/package/react-dom) and

```
this.setSelectionIfNeeded(ReactDOM.findDOMNode(this));
```

Happy to help out if you'd like a PR.

**Comment by quantizor** [comment]
@craigdallimore Hey, yup we are not updated for 0.14 as of yet. PRs welcome. Note that the final code needs to be backward compatible with <0.13

**Comment by craigdallimore** [comment]
> Note that the final code needs to be backward compatible with <0.13

Hello @yaycmyk!

I'm not quite sure that there is a good way to satisfy both sides of the breaking change - 0.13 uses `this.getDOMNode()` and 0.14 prefers `ReactDOM.findDOMNode(this)`.

I believe the point of the warning is to push us to change how we access nodes, as `this.getDOMNode` is [probably not going to work in 0.15](https://github.com/facebook/react/issues/4600).

Is it not acceptable to have a new release that expects `^react@0.14` and let `react@0.13` users stay on `react-input-placeholder@1.x?`

**Comment by quantizor** [comment]
I'm planning on a rewrite for 2.0.0 that will utilize 0.14
